roles-list:
  - lob : "CB"
    message : "hello"
  - lob : "CIB"
    message : "Wow"
server:
    port: 8090
test: "Testing"
roles:
  list:
    - lob: CB
      message: hello
    - lob: CIB
      message: Wow
foo.foo1:
  list:
    step1:
      0:
        cool: qwe
      1:
        cool: qwe
        warm: we
        cold: wee
      2:
        cool: qwe
    step2:
      0:
        cool: qwe
        warm: we
        cold: wee
spring.main.allow-circular-references : true
